#!/bin/bash
set -e

echo "=== CRM Firebase Function Deploy ==="
echo ""

echo "[1/5] Generating functions-crm/.env from root .env..."
# Extracts keys needed by the CRM Cloud Function from the single root .env.
# You never need to edit functions-crm/.env directly.
_read_env() {
  grep -E "^${1}=" .env 2>/dev/null | head -1 | sed "s/^${1}=//;s/^['\"]//;s/['\"]$//"
}
{
  echo "# Auto-generated by deploy_crm.sh — edit root .env instead"
  echo "BATCH_RUNNER_URL=$(_read_env BATCH_RUNNER_URL)"
  echo "BATCH_SECRET=$(_read_env BATCH_SECRET)"
  echo "BATCH_SA=$(_read_env BATCH_SA)"
} > functions-crm/.env
echo "  Written functions-crm/.env (BATCH_RUNNER_URL, BATCH_SECRET, BATCH_SA)"

echo "[2/5] Setting up venv..."
for FDIR in functions-crm; do
  if [ ! -f "$FDIR/venv/Scripts/activate" ] && [ ! -f "$FDIR/venv/bin/activate" ]; then
    echo "  creating $FDIR/venv..."
    python -m venv "$FDIR/venv"
  else
    echo "  $FDIR/venv exists"
  fi
done

echo "[3/5] Installing/updating requirements..."
for FDIR in functions-crm; do
  echo "  $FDIR..."
  "$FDIR/venv/Scripts/pip.exe" install -r "$FDIR/requirements.txt" -q 2>/dev/null || \
  "$FDIR/venv/bin/pip"         install -r "$FDIR/requirements.txt" -q
done

echo "[4/5] Deploying functions to Firebase..."
firebase deploy --only functions

echo "[5/5] Deploying hosting (CRM dashboard)..."
firebase deploy --only hosting

echo ""
echo "=== Deploy Complete ==="
echo ""
echo "Dashboard:"
echo "  https://blueboot-market.web.app/"
echo ""
